sudo: required
services:
  - docker

env:
    global:
        - DOCKER_VERSION=17.07.0~ce-0~ubuntu

before_install:
  - sudo apt-cache madison docker-ce
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-ce=${DOCKER_VERSION}
  - docker version
  - docker pull mbodenhamer/texlive:latest

script:
  - make test